services:
  roll-plugin-monitor:
    image: 203.228.107.184:5000/btx/roll_plugin_monitor:1.0.6
    container_name: roll-plugin-monitor
    restart: unless-stopped
    environment:
      DISPLAY: ${DISPLAY:-:0}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./roll_plugin_monitor/config.ini:/app/config/config.ini:ro
      - ./roll_plugin_monitor/logs:/app/logs
    network_mode: host
